FROM python:3.11-alpine

ADD requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

RUN apk update \
  && apk upgrade \
  && apk add bash jq \
  && rm -rf /var/cache/*/*
